# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0002_auto_20160820_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('resultado', models.IntegerField()),
                ('modalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='deportista',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='resultado',
        ),
        migrations.AddField(
            model_name='deportista',
            name='urlImagen',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='deportista',
            name='urlVideo',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
        migrations.AddField(
            model_name='evento',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimpicolombiaApp.Deportista'),
        ),
    ]
