# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0003_auto_20160823_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='deporte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='olimpicolombiaApp.Deporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='urlImagen',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='urlVideo',
            field=models.CharField(max_length=1000),
        ),
    ]
