# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0004_auto_20160823_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='deporte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='olimpicolombiaApp.Deporte'),
        ),
    ]
