# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0005_auto_20160823_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='deporte',
        ),
    ]
