# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0008_auto_20160823_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='estatura',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='peso',
            field=models.IntegerField(null=True),
        ),
    ]
