# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0009_auto_20160823_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='estatura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
