# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:45
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombiaApp', '0010_auto_20160823_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='urlVideo',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
