# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpicolombia01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('lugarNacimiento', models.CharField(max_length=120)),
                ('fechaNacimiento', models.DateField()),
                ('entrenador', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg', max_length=1000),
            preserve_default=False,
        ),
    ]
